// Portfolio Data
const PROJECTS = [
  {
    id: "kpoin",
    kind: "Real Project",
    title: "KPoin Point of Sales — Multi Store Order Management System",
    subtitle: "Enterprise dashboard · Multi-store chain management",
    chips: ["Dashboard", "SaaS"],
    role: "Product Designer",
    year: "2023-2024",
    duration: "12 weeks",
    team: "1 designer, 4 engineers, 1 PM",
    cover: "dashboard",
    coverImg: "pos-order.webp",
    projectInfo: [
      { l: "Role", v: "Product Designer" },
      { l: "Year", v: "2023-2024" },
      { l: "Duration", v: "12 weeks" },
      { l: "Team", v: "1 designer, 4 engineers, 1 PM" },
    ],
    accent: "#3D55CC",
    demo: "https://lillbram.github.io/pos-demo/",
    summary:
      "A unified POS and operational intelligence platform for multi-store restaurant chains. Reduced order time 7x, eliminated 90% of errors, and enabled same-day financial decisions.",
    body: [],
    sections: [
      {
        type: "stats",
        items: [
          {
            value: "7×",
            label: "Faster Orders",
            sub: "15-20 min → 2-3 min",
            color: "#3D55CC",
          },
          {
            value: "90%",
            label: "Fewer Errors",
            sub: "8-12% → <1%",
            color: "#10B981",
          },
          {
            value: "75%",
            label: "Less Waste",
            sub: "Rp 40M+ saved / year",
            color: "#F59E0B",
          },
          {
            value: "16%",
            label: "Better Retention",
            sub: "68% → 84%",
            color: "#8B5CF6",
          },
        ],
      },
      {
        type: "text",
        content:
          "Multi-store restaurant chains were operating as silos. Each location ran its own POS, inventory, and financials — no cross-location visibility, 10-15% inventory waste, and P&L only visible at month-end. The challenge wasn't building more features — it was eliminating friction at every step of the operation.",
      },
      {
        type: "demo-cta",
        url: "https://lillbram.github.io/pos-demo/",
        label: "Explore Live Demo",
        note: "Full system with real demo data — no login required",
      },
      {
        type: "heading",
        label: "01 — Research",
        title: "5 Problems Destroying Profitability",
      },
      {
        type: "problems",
        items: [
          {
            num: "01",
            title: "Fragmented Data",
            pain: "Each store operates as an independent silo with zero cross-location visibility",
            impact:
              "Strategic decisions delayed. Local optimization actively hurts company-wide profitability.",
            severity: "high",
          },
          {
            num: "02",
            title: "Slow Order Processing",
            pain: "Manual 7-step entry averages 15-20 minutes per order with 8-12% error rate",
            impact:
              "Customer frustration. Revenue loss at peak hours. Staff overwhelmed with rework.",
            severity: "high",
          },
          {
            num: "03",
            title: "No Financial Visibility",
            pain: "P&L reports only appear at month-end — 35+ days after transactions occur",
            impact:
              "Reactive decisions only. Preventable losses discovered far too late to fix.",
            severity: "high",
          },
          {
            num: "04",
            title: "Scattered Customer Data",
            pain: "VIP customers not recognized across locations. History siloed per store.",
            impact:
              "Lost upsell opportunities. 32% churn. Personalization impossible.",
            severity: "medium",
          },
          {
            num: "05",
            title: "Inventory Chaos",
            pain: "One store overstocked while another runs out. Manual ordering: 90 min/week.",
            impact: "8-12% stockout rate. Unnecessary supply chain costs.",
            severity: "medium",
          },
        ],
      },
      {
        type: "heading",
        label: "02 — Solution",
        title: "From Friction to Flow",
      },
      {
        type: "comparison",
        rows: [
          {
            metric: "Order processing time",
            before: "15-20 min",
            after: "2-3 min",
            tag: "7× faster",
          },
          {
            metric: "Data entry error rate",
            before: "8-12%",
            after: "<1%",
            tag: "90% fewer",
          },
          {
            metric: "P&L visibility",
            before: "35 days",
            after: "Real-time",
            tag: "Instant",
          },
          {
            metric: "Stock Expired Wasted",
            before: "10-15%",
            after: "2-3%",
            tag: "75% less",
          },
          {
            metric: "Staff time on data entry",
            before: "60% of shift",
            after: "10% of shift",
            tag: "50 min/day saved",
          },
          {
            metric: "Customer retention",
            before: "68%",
            after: "84%",
            tag: "+16 pts",
          },
        ],
      },
      {
        type: "heading",
        label: "03 — Design Decisions",
        title: "What Made the Difference",
      },
      {
        type: "decisions",
        items: [
          {
            num: "D1",
            title: "Two-Role System",
            why: "Cashiers and managers have completely different operational needs",
            how: "Cashier sees: Orders only. Admin sees: Full reports, finance, staff, config.",
            result: "40% less navigation, near-zero misconfiguration incidents",
          },
          {
            num: "D2",
            title: "Color-Coded Status",
            why: "Reading text labels in a busy restaurant environment takes too long",
            how: "Green = OK. Yellow = Monitor. Red = Act now. Applied across inventory, finance, customers.",
            result:
              "System state understood in under 1 second, no reading required",
          },
          {
            num: "D3",
            title: "Real-Time Everywhere",
            why: "Batch processing creates lag, distrust, and fatally delayed decisions",
            how: "Every change updates instantly. No Save button. No confirmation delays anywhere.",
            result:
              "90% fewer errors, same-day financial decision-making enabled",
          },
          {
            num: "D4",
            title: "Multi-Store by Default",
            why: "Local optimization often silently hurts company-wide performance",
            how: "Inventory and finance default to all-stores view. Drill-down available.",
            result:
              "Strategic thinking replaced local tunnel vision across all managers",
          },
          {
            num: "D5",
            title: "Promos in Order Flow",
            why: "A separate promo module adds steps and kills compliance",
            how: "Best promo auto-applies during checkout. One tap to change or override.",
            result: "Faster checkout, higher compliance, cleaner promo data",
          },
        ],
      },
      {
        type: "heading",
        label: "04 — Design System",
        title: "Visual Language Built for Operations",
      },
      { type: "design-system" },
      {
        type: "heading",
        label: "05 — Information Architecture",
        title: "Role-Based Navigation, Not Feature-Based",
      },
      { type: "ia" },
      {
        type: "heading",
        label: "06 — Impact",
        title: "Measurable Business Results",
      },
      {
        type: "impact",
        items: [
          {
            label: "Order Time",
            before: 18,
            after: 2.5,
            unit: "min",
            tag: "7× faster",
          },
          {
            label: "Error Rate",
            before: 10,
            after: 0.5,
            unit: "%",
            tag: "90% fewer",
          },
          {
            label: "Expired Stock Waste",
            before: 13,
            after: 2.5,
            unit: "%",
            tag: "75% less",
          },
          {
            label: "Customer Retention",
            before: 68,
            after: 84,
            unit: "%",
            tag: "+16 pts",
            higher_is_better: true,
          },
        ],
      },
      {
        type: "quote",
        text: "Make the complex simple through ruthless prioritization.",
        sub: "— Design philosophy, KPoin Point of Sales",
      },
      {
        type: "heading",
        label: "07 — Design Overview",
        title: "Design Overview — Key Screens",
      },
      {
        type: "core-pages",
        pages: [
          {
            title: "Order screen",
            subtitle: "Cashier's primary workspace",
            tag: "Core feature",
            tagColor: "#3D55CC",
            img: "pos-order.webp",
            url: "https://lillbram.github.io/pos-demo/order.html",
            desc: "The main cashier workspace. Staff use this to build and complete customer orders in real time – picking products, applying discounts, and collecting payment without leaving the screen.",
            features: [
              "Browse products by category or search by name/barcode",
              "Supports dine-in, take-away, and delivery order types",
              "Apply promo codes before checkout",
              "Pay via cash, card, or QR code",
              "Hold orders and retrieve them later",
            ],
          },
          {
            title: "Products & inventory",
            subtitle: "Stock and product management",
            tag: "Management",
            tagColor: "#10B981",
            img: "pos-inventory.webp",
            url: "https://lillbram.github.io/pos-demo/inventory.html",
            desc: "The full catalog of all products across every store. Admins manage what's on the menu, how much it costs, and how much stock is left – all from one table view.",
            features: [
              "View SKU, price, and total stock per product",
              "Filter by category and sort by newest, name, or SKU",
              "Loyalty points earned per product",
              "Create new products or edit existing ones",
              "Stock status indicators (In Stock / Low / Out)",
            ],
          },
          {
            title: "Customers",
            subtitle: "Loyalty and customer directory",
            tag: "Management",
            tagColor: "#10B981",
            img: "pos-customers.webp",
            url: "https://lillbram.github.io/pos-demo/customer.html",
            desc: "A complete view of every registered customer and their activity. Tracks loyalty points, order history, and membership status so the team can identify and reward top customers.",
            features: [
              "See loyalty point balance per customer",
              "VIP badge for high-value members",
              "Daily snapshot of new, returning, and walk-in customers",
              "Register new customers directly from this page",
              "Search by name or phone number",
            ],
          },
          {
            title: "Summary report",
            subtitle: "Daily and period-level analytics",
            tag: "Reports",
            tagColor: "#EC4899",
            img: "pos-summary-report.webp",
            url: "https://lillbram.github.io/pos-demo/report.html",
            desc: "A daily business health check for managers. Shows revenue, transactions, promo usage, and profit margin at a glance – with trend charts to spot patterns over the last 7 days.",
            features: [
              "Total revenue, transactions, and average order value",
              "Gross profit breakdown with margin percentage",
              "Sales trend line chart (last 7 days)",
              "Top 5 best-selling products",
              "Export as PDF for sharing with stakeholders",
            ],
          },
          {
            title: "Detail report",
            subtitle: "Transaction-level drill-down analytics",
            tag: "Reports",
            tagColor: "#EC4899",
            img: "pos-detail-report.webp",
            url: "https://lillbram.github.io/pos-demo/report.html",
            desc: "A deep-dive into every transaction within a selected date range. Lets managers drill down by product, promo, store, or inventory movement to understand exactly what's driving revenue.",
            features: [
              "Filter by date range, store, and category",
              "Sales breakdown with per-product COGS and margin",
              "Promo analytics tab to measure discount ROI",
              "Inventory movement and store comparison tabs",
              "Paginated table with export option",
            ],
          },
          {
            title: "P&L summary",
            subtitle: "P&L statement and financial health",
            tag: "Finance",
            tagColor: "#0EA5E9",
            img: "pos-finance.webp",
            url: "https://lillbram.github.io/pos-demo/finance.html",
            desc: "A formal profit and loss statement that gives owners a complete financial picture – from gross sales down to net profit, accounting for COGS, staff salaries, rent, and taxes.",
            features: [
              "Full income statement: revenue, COGS, gross profit, operating expenses, net profit",
              "Period comparison vs previous period",
              "Key performance insights panel",
              "Revenue allocation donut chart",
              "Filter by store and time period",
            ],
          },
          {
            title: "Promo & discount",
            subtitle: "Campaign and promotion control",
            tag: "Management",
            tagColor: "#10B981",
            img: "pos-promo.webp",
            url: "https://lillbram.github.io/pos-demo/promo.html",
            desc: "The control panel for all active promotional codes. Admins can create, monitor, and manage discounts – choosing between fixed amount or percentage off, scoped per transaction or per product.",
            features: [
              "View all active promo codes in one table",
              "Supports percentage and fixed amount discount types",
              "Track how many promos were applied today and total savings given",
              "Assign promos to specific stores",
              "Create or delete promo codes instantly",
            ],
          },
          {
            title: "Staff list",
            subtitle: "Team and role administration",
            tag: "Management",
            tagColor: "#10B981",
            img: "pos-staff.webp",
            url: "https://lillbram.github.io/pos-demo/staff.html",
            desc: "A directory of all staff across every outlet. Shows who works where, what role they hold, and their status – so admins can manage access and store coverage from one place.",
            features: [
              "View all staff with role (Admin / Manager / Cashier)",
              "See which stores each staff member is assigned to",
              "Active and inactive staff counts at a glance",
              "Add, edit, or remove staff",
              "Search by name",
            ],
          },
          {
            title: "Store list",
            subtitle: "Multi-location configuration",
            tag: "Management",
            tagColor: "#10B981",
            img: "pos-store.webp",
            url: "https://lillbram.github.io/pos-demo/store.html",
            desc: "An overview of every outlet in the network. Tracks each store's address, staff count, stocked products, and active promotions – giving admins a bird's-eye view of the entire operation.",
            features: [
              "List of all outlets with location and contact info",
              "See stocked products and unit count per store",
              "Global stock unit total across all outlets",
              "Add new store outlets",
              "Edit or remove existing stores",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "career-solution",
    kind: "Real Project",
    title: "Career Solution — Mobile Job Platform",
    subtitle: "Mobile PWA · Job search & career development",
    chips: ["Mobile App", "PWA"],
    role: "Product Designer",
    year: "2022",
    duration: "8 weeks",
    team: "1 designer, 2 engineers, 1 PM",
    cover: "career",
    coverImg: "career-solution.webp",
    projectInfo: [
      { l: "Role", v: "roduct Designer" },
      { l: "Year", v: "2022" },
      { l: "Duration", v: "8 weeks" },
      { l: "Team", v: "1 designer, 2 engineers, 1 PM" },
    ],
    accent: "#10B981",
    demo: "https://lillbram.github.io/career-solution-pwa/",
    summary:
      "A mobile-first job platform PWA that simplifies the entire hiring journey — from discovery to one-tap application to real-time offer tracking. Built for Indonesia's growing job market with smart job matching and direct recruiter messaging.",
    body: [],
    sections: [
      {
        type: "stats",
        items: [
          {
            value: "3×",
            label: "Faster Apply",
            sub: "8 steps → 1 tap",
            color: "#1E9E6B",
          },
          {
            value: "68%",
            label: "Completion Rate",
            sub: "vs 35% industry avg",
            color: "#10B981",
          },
          {
            value: "2×",
            label: "More Job Matches",
            sub: "Smart recommendations",
            color: "#F59E0B",
          },
          {
            value: "45%",
            label: "Better Retention",
            sub: "Notifications + tracking",
            color: "#8B5CF6",
          },
        ],
      },
      {
        type: "text",
        content:
          "Job seekers in Indonesia were navigating fragmented hiring experiences — outdated listings, multi-step application forms, and zero visibility after submitting. Recruiters struggled to reach the right candidates efficiently. The challenge wasn't building another job board — it was removing every barrier between a qualified candidate and their next opportunity.",
      },
      {
        type: "demo-cta",
        url: "https://lillbram.github.io/career-solution-pwa/",
        label: "Explore Live Demo",
        note: "Full system with demo data — no login required",
      },
      {
        type: "heading",
        label: "01 — Research",
        title: "5 Barriers Blocking Job Seekers",
      },
      {
        type: "problems",
        items: [
          {
            num: "01",
            title: "Friction-Heavy Applications",
            pain: "Traditional apply flows require 8+ steps: forms, uploads, re-typing resume data",
            impact:
              "65% abandonment rate at the application step. Qualified candidates lost before even being seen.",
            severity: "high",
          },
          {
            num: "02",
            title: "Zero Status Visibility",
            pain: "After submitting, candidates hear nothing. No confirmation, no timeline, no status updates",
            impact:
              "Anxiety, repeated follow-ups, and 40% of candidates reapplying to the same role by mistake.",
            severity: "high",
          },
          {
            num: "03",
            title: "Irrelevant Job Listings",
            pain: "Generic search returns mismatched results — wrong salary range, location, or seniority level",
            impact:
              "Time wasted reviewing unsuitable roles. Trust in the platform erodes after repeated mismatches.",
            severity: "high",
          },
          {
            num: "04",
            title: "No Direct Recruiter Access",
            pain: "Candidates cannot communicate with recruiters — only one-way form submissions allowed",
            impact:
              "Missed context, misaligned expectations, and delayed hiring decisions on both sides.",
            severity: "medium",
          },
          {
            num: "05",
            title: "Resume Management Chaos",
            pain: "Candidates maintain multiple resume versions outside the platform, re-uploading each time",
            impact:
              "Wrong resume attached 18% of the time. Outdated profile data shared with employers.",
            severity: "medium",
          },
        ],
      },
      {
        type: "heading",
        label: "02 — Solution",
        title: "From Friction to First Interview",
      },
      {
        type: "comparison",
        rows: [
          {
            metric: "Steps to apply",
            before: "8+ steps",
            after: "1 tap",
            tag: "3× faster",
          },
          {
            metric: "Application completion rate",
            before: "35%",
            after: "68%",
            tag: "+33 pts",
          },
          {
            metric: "Status visibility",
            before: "None",
            after: "Real-time",
            tag: "Instant",
          },
          {
            metric: "Job match relevance",
            before: "Generic search",
            after: "Smart recommendations",
            tag: "2× better",
          },
          {
            metric: "Resume accuracy rate",
            before: "82%",
            after: "99%",
            tag: "Saved resumes",
          },
          {
            metric: "Recruiter response time",
            before: "5-7 days",
            after: "< 24 hours",
            tag: "Direct chat",
          },
        ],
      },
      {
        type: "heading",
        label: "03 — Design Decisions",
        title: "What Made the Difference",
      },
      {
        type: "decisions",
        items: [
          {
            num: "D1",
            title: "One-Tap Apply",
            why: "Every extra step in the apply flow costs ~15% of remaining applicants",
            how: "Profile and preferred resume pre-selected. One button submits with optional cover letter.",
            result:
              "Application completion rate jumped from 35% to 68% in first cohort",
          },
          {
            num: "D2",
            title: "Real-Time Status Tracking",
            why: "Post-apply silence was the #1 complaint in user research across all age groups",
            how: "4-stage pipeline visible: Received → Under Review → Shortlisted → Decision. Push alerts on each change.",
            result:
              "Support tickets about application status dropped to near zero",
          },
          {
            num: "D3",
            title: "Smart Job Recommendations",
            why: "Generic search results destroy trust faster than no results at all",
            how: "Home feed ranks jobs by title match, salary range, location, and prior application patterns.",
            result: "2× increase in job detail opens vs browse-only users",
          },
          {
            num: "D4",
            title: "Multi-Resume Management",
            why: "Candidates tailor resumes per role — forcing one resume leads to wrong attachments",
            how: "Save up to 3 named resumes. Default is auto-selected but swappable in one tap before submit.",
            result:
              "Wrong resume incidents eliminated. Profile accuracy reached 99%",
          },
          {
            num: "D5",
            title: "Direct Recruiter Chat",
            why: "Hiring decisions stall when candidates and recruiters can't communicate directly",
            how: "In-app messaging thread per application. Recruiter initiates; candidate responds in context.",
            result:
              "Average time to first interview response dropped from 5-7 days to under 24 hours",
          },
        ],
      },
      {
        type: "heading",
        label: "04 — Design System",
        title: "Visual Language Built for Trust",
      },
      { type: "design-system-career" },
      {
        type: "heading",
        label: "05 — Information Architecture",
        title: "Job Seeker-First Navigation",
      },
      { type: "ia" },
      {
        type: "heading",
        label: "06 — Impact",
        title: "Measurable Results",
      },
      {
        type: "impact",
        items: [
          {
            label: "Apply Steps",
            before: 8,
            after: 1,
            unit: " steps",
            tag: "3× faster",
            higher_is_better: false,
          },
          {
            label: "Completion Rate",
            before: 35,
            after: 68,
            unit: "%",
            tag: "+33 pts",
            higher_is_better: true,
          },
          {
            label: "Recruiter Response",
            before: 6,
            after: 1,
            unit: " days",
            tag: "6× faster",
            higher_is_better: false,
          },
          {
            label: "Job Match Rate",
            before: 40,
            after: 80,
            unit: "%",
            tag: "2× better",
            higher_is_better: true,
          },
        ],
      },
      {
        type: "quote",
        text: "Remove every barrier between a great candidate and their next opportunity.",
        sub: "— Design philosophy, Career Solution",
      },
      {
        type: "heading",
        label: "07 — Design Overview",
        title: "Design Overview — Key Screens",
      },
      {
        type: "core-pages",
        pages: [
          {
            title: "Home Dashboard",
            subtitle: "Progress overview & recommendations",
            tag: "Core Feature",
            tagColor: "#1E9E6B",
            img: "career-home.webp",
            url: "https://lillbram.github.io/career-solution-pwa/",
            desc: "The first screen after login. A green profile completion banner (85%) prompts the next action. A 4-stat row shows Applications, Interviews, Saved Jobs, and Profile Views. Below it, 'Check your latest applications' surfaces recent activity, and 'Recommended job for you' delivers personalised listings with salary, work type, and experience tags.",
            features: [
              "Profile completion banner with % and one-line next step",
              "4-stat row: Applications, Interviews, Saved Jobs, Profile Views",
              "Latest applications with real-time status badge (Applied, Review)",
              "Recommended jobs feed with salary range and work type tags",
              "Notification bell for real-time recruiter and status alerts",
            ],
          },
          {
            title: "Find Opportunities",
            subtitle: "Search & filter job listings",
            tag: "Discovery",
            tagColor: "#1E9E6B",
            img: "career-search.webp",
            url: "https://lillbram.github.io/career-solution-pwa/",
            desc: "The main job discovery screen. A full-width search bar accepts job title, company, or keyword. Filter chips for All, Remote, Hybrid, On-site, and Product category let candidates narrow results instantly. Each card shows company icon, title, company + city, salary range in green, work type tag, experience tag, a save star, and an inline Apply button — 6 jobs found in the demo.",
            features: [
              "Search bar: 'Search job title, company…' — title, skills, or company",
              "Filter chips: All (active), Remote, Hybrid, On-site, Product category",
              "Salary range shown in green on every card before any tap",
              "Work type tags (Remote, Hybrid, Full-time) + experience level tags",
              "Inline Apply button and star save on each listing — no drill-in needed",
            ],
          },
          {
            title: "Job Detail",
            subtitle: "Full listing with sticky apply CTA",
            tag: "Core Feature",
            tagColor: "#1E9E6B",
            img: "career-job-detail.webp",
            url: "https://lillbram.github.io/career-solution-pwa/",
            desc: "Full job page for Senior Product Designer at Gojek. A compact 4-column meta strip at the top shows Type (Full-time), Salary (Rp 100–135M), Experience (3–5 Years), and Location (Remote) at a glance — no scrolling required. Key Responsibilities, Qualifications, and What We Offer sections follow. A sticky full-width 'Submit application' button is pinned to the bottom so it's always reachable.",
            features: [
              "Company icon + title + 'DKI Jakarta · 2 Days Ago · 100+ Applicant'",
              "4-column meta strip: Type, Salary, Experience, Location — always visible",
              "Key Responsibilities section with full role description",
              "Qualifications list and What We Offer benefits section",
              "Sticky full-width 'Submit application' CTA pinned to bottom",
            ],
          },
          {
            title: "Apply Flow",
            subtitle: "Resume selection & one-tap submit",
            tag: "Core Feature",
            tagColor: "#1E9E6B",
            img: "career-apply.webp",
            url: "https://lillbram.github.io/career-solution-pwa/",
            desc: "Single-screen apply flow for Senior Product Designer. A transparency notice confirms 'Your profile will be shared with the employer'. Three saved resumes are listed — two Career Solution Resumes and one custom file — each with Edit or Preview actions. The first resume is highlighted in mint green as the selected choice. An 'Add / Create Resume' option sits below. A sticky green 'Continue' button closes the flow.",
            features: [
              "'Your profile will be shared with the employer' — transparency upfront",
              "3 saved resumes listed: Career Solution Resume × 2, Your own Resume",
              "Selected resume highlighted with green border (mint background)",
              "Edit or Preview actions on each saved resume",
              "Sticky full-width 'Continue' CTA — one tap to submit",
            ],
          },
          {
            title: "My Jobs",
            subtitle: "Application pipeline tracker",
            tag: "Tracking",
            tagColor: "#F59E0B",
            img: "career-tracker.webp",
            url: "https://lillbram.github.io/career-solution-pwa/",
            desc: "All submitted applications in one filtered list. Three tab pills — All (4), Active (2), Rejected (1) — let candidates focus on what matters. Each row shows company icon, job title, company + city, application date, and a colour-coded status badge: Applied (blue), Review (gray), Approved (green), Rejected (pink). Tap any row to open the full application or recruiter messages.",
            features: [
              "Filter tabs with live counts: All 4, Active 2, Rejected 1",
              "Status badges: Applied (blue), Review (gray), Approved (green), Rejected (pink)",
              "UX Researcher @ Tokopedia — Applied 3 days ago",
              "Visual Designer @ Traveloka — Under Review",
              "Interaction Designer @ Bukalapak — Approved · Product Manager @ Shopee — Rejected",
            ],
          },
          {
            title: "Create Profile",
            subtitle: "Candidate identity & resume builder",
            tag: "Management",
            tagColor: "#8B5CF6",
            img: "career-profile.webp",
            url: "https://lillbram.github.io/career-solution-pwa/",
            desc: "Structured profile builder with four sections: Basic Info (Job Title, Location, Portfolio URL, About/Bio), Work Experience with + Add for multiple entries, Education, and Skills (Figma, UX Research, Prototyping, Design Systems, User Testing). Each field uses a subtle green outline. Individual entries can be removed with the × button. A sticky 'Save Profile' CTA sits at the bottom.",
            features: [
              "Basic Info: Job Title, Location, Portfolio URL, About/Bio textarea",
              "Work Experience: multiple entries, each removable with ×, + Add for more",
              "Education section with the same pattern as work experience",
              "Skills section: add tags (Figma, UX Research, Prototyping, Design Systems…)",
              "Sticky 'Save Profile' button — all sections saved in one tap",
            ],
          },
          {
            title: "Recruiter Messages",
            subtitle: "Per-application inbox",
            tag: "Communication",
            tagColor: "#0EA5E9",
            img: "career-chat.webp",
            url: "https://lillbram.github.io/career-solution-pwa/",
            desc: "A unified inbox showing one conversation thread per application. Filter pills — All (4), Read (2), Unread (2) — help candidates prioritise. Each row shows the recruiter company, message preview, and timestamp. Companies in the demo: Tokopedia Hiring, Traveloka Careers, Bukalapak Opportunities, Grab Talent Acquisition. Tapping a thread opens a full in-app chat with full message history.",
            features: [
              "Inbox filter: All 4, Read 2, Unread 2",
              "One thread per application — no context switching between apps",
              "Company name as thread title (Tokopedia Hiring, Traveloka Careers…)",
              "Message preview and relative timestamp per row",
              "Unread badge count on Messages tab in bottom nav",
            ],
          },
          {
            title: "Subscription Plans",
            subtitle: "Free vs Pro — choose your tier",
            tag: "Monetisation",
            tagColor: "#EC4899",
            img: "career-plans.webp",
            url: "https://lillbram.github.io/career-solution-pwa/",
            desc: "'Choose Your Plan — Upgrade anytime. Cancel anytime.' Two tiers side by side. Free (Rp 0/forever): browse up to 20 jobs/day, apply to 5/month, basic profile, status tracking, email notifications — shown with 'Current Plan' button. Pro (Rp 49.000/month) in a dark green filled card with 'Most Popular' badge: unlimited browsing, unlimited applications, priority profile visibility, advanced analytics, resume builder & export, direct message employers, job alerts.",
            features: [
              "Free: browse 20/day, apply 5/month, basic profile, status tracking",
              "Pro Rp 49.000/month: unlimited browsing + unlimited applications",
              "Pro: priority profile visibility + advanced profile analytics",
              "Pro: resume builder & export, direct message employers",
              "'Most Popular' badge on Pro — 'Subscribe Pro' CTA on dark green card",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "skillbooster",
    kind: "Real Project",
    title: "Skill Booster — E-Learning Mobile Platform",
    subtitle: "Mobile PWA · Online courses & seminars",
    chips: ["Mobile App", "PWA"],
    role: "Lead Product Designer",
    year: "2024",
    duration: "16 weeks",
    team: "1 designer, 5 engineers, 1 PM",
    cover: "elearning",
    coverImg: "skill-booster.webp",
    projectInfo: [
      { l: "Role", v: "Product Designer" },
      { l: "Year", v: "2022" },
      { l: "Duration", v: "8 weeks" },
      { l: "Team", v: "1 designer, 2 engineers, 1 PM" },
    ],
    accent: "#4F46E5",
    demo: "https://lillbram.github.io/skillbooster-pwa/",
    summary:
      "A mobile-first e-learning PWA that turns scattered online courses into a structured learning journey — from discovery to enrollment to completion tracking. Built for self-paced learners who want career-relevant skills without friction.",
    body: [],
    sections: [
      {
        type: "stats",
        items: [
          {
            value: "4×",
            label: "Faster Discovery",
            sub: "Browse → Smart recommendations",
            color: "#4F46E5",
          },
          {
            value: "82%",
            label: "Completion Rate",
            sub: "vs 45% industry avg",
            color: "#10B981",
          },
          {
            value: "3×",
            label: "More Enrollments",
            sub: "Per active user/month",
            color: "#F59E0B",
          },
          {
            value: "55%",
            label: "Better Retention",
            sub: "Progress tracking + reminders",
            color: "#8B5CF6",
          },
        ],
      },
      {
        type: "text",
        content:
          "Online learners in Indonesia were dropping courses within the first week — not because the content was bad, but because the experience was. Overwhelming catalogs, no progress tracking, and a hard paywall before learners knew if a course was right for them. The challenge wasn't building another course platform — it was designing a learning journey that felt worth finishing.",
      },
      {
        type: "demo-cta",
        url: "https://lillbram.github.io/skillbooster-pwa/",
        label: "Explore Live Demo",
        note: "Full system with demo data — no account required",
      },
      {
        type: "heading",
        label: "01 — Research",
        title: "5 Reasons Learners Quit",
      },
      {
        type: "problems",
        items: [
          {
            num: "01",
            title: "Overwhelming Course Catalog",
            pain: "Hundreds of courses with no personalization — learners scroll endlessly without finding the right fit",
            impact:
              "70% of new users leave within 3 minutes of browsing without enrolling in anything.",
            severity: "high",
          },
          {
            num: "02",
            title: "No Progress Visibility",
            pain: "Learners have no clear sense of how far through a course they are or what comes next",
            impact:
              "55% of enrolled learners never return after the first lesson — no hook to come back.",
            severity: "high",
          },
          {
            num: "03",
            title: "Paywall Before Value",
            pain: "Courses require payment before learners can see any content — no free preview available",
            impact:
              "High drop-off at checkout. Learners won't pay for something they haven't sampled.",
            severity: "high",
          },
          {
            num: "04",
            title: "No Live Learning Options",
            pain: "Platform only offers recorded courses — no real-time events, seminars, or cohort learning",
            impact:
              "Learners seeking accountability and interaction leave for competing platforms.",
            severity: "medium",
          },
          {
            num: "05",
            title: "Fragmented Learning Library",
            pain: "No unified view of purchased courses and registered events — they live in different places",
            impact:
              "Learners forget what they've enrolled in. Paid courses sit unwatched.",
            severity: "medium",
          },
        ],
      },
      {
        type: "heading",
        label: "02 — Solution",
        title: "From Browsing to Completing",
      },
      {
        type: "comparison",
        rows: [
          {
            metric: "Course discovery",
            before: "Browse full catalog",
            after: "Personalized home feed + smart recs",
            tag: "4× faster",
          },
          {
            metric: "Completion rate",
            before: "45% industry avg",
            after: "82%",
            tag: "+37 pts",
          },
          {
            metric: "Paywall friction",
            before: "Pay to see anything",
            after: "Free lesson previews first",
            tag: "Reduced drop-off",
          },
          {
            metric: "Learning continuity",
            before: "Restart from beginning",
            after: "Resume from last lesson",
            tag: "Auto-save",
          },
          {
            metric: "Live learning",
            before: "Not available",
            after: "Integrated seminar events",
            tag: "New channel",
          },
          {
            metric: "Library overview",
            before: "Courses only",
            after: "Courses + events + progress",
            tag: "Unified",
          },
        ],
      },
      {
        type: "heading",
        label: "03 — Design Decisions",
        title: "What Made the Difference",
      },
      {
        type: "decisions",
        items: [
          {
            num: "D1",
            title: "Curated Home Feed",
            why: "A blank catalog forces learners to know what they want before they know what exists",
            how: "Home shows a featured hero banner, 'New This Week', 'Trending Now', personalized recommendations, and highest-rated picks — each with a single clear CTA.",
            result:
              "Enrollment from home feed increased 4× vs direct catalog browsing",
          },
          {
            num: "D2",
            title: "Progress-First Library",
            why: "Learners abandon courses they can't see themselves finishing",
            how: "Library shows each course with a progress bar (0–100%), completion checkmark, and direct resume button. Events show status (Incoming / Running) with countdown.",
            result: "Course return rate rose from 45% to 82% in first cohort",
          },
          {
            num: "D3",
            title: "Free Lesson Previews",
            why: "Learners won't pay for content they haven't sampled — the paywall kills intent",
            how: "Each course has 2-3 lessons marked 'Preview' — visible before enrollment. Checkout is triggered from the course detail after the learner has seen real value.",
            result:
              "Checkout conversion improved 3× over hard-paywall baseline",
          },
          {
            num: "D4",
            title: "Integrated Seminar Events",
            why: "Recorded-only platforms lose learners who want live interaction and accountability",
            how: "Explore tab has a dedicated Events section alongside courses. Seminar cards show date, host, location, and price. Registration is a single tap.",
            result:
              "20% of active learners registered for at least one seminar per month",
          },
          {
            num: "D5",
            title: "Freemium Subscription Tier",
            why: "A single paid-only tier locks out the majority of potential users who could convert later",
            how: "Free tier allows course browsing and limited previews. Premium unlocks unlimited enrollment, downloads, and certificates. Profile shows subscription status with a clear upgrade path.",
            result:
              "Free-to-Premium conversion rate reached 28% among 30-day active users",
          },
        ],
      },
      {
        type: "heading",
        label: "04 — Design System",
        title: "Visual Language Built for Learning",
      },
      { type: "design-system-skillboost" },
      {
        type: "heading",
        label: "05 — Impact",
        title: "Measurable Results",
      },
      {
        type: "impact",
        items: [
          {
            label: "Discovery Time",
            before: 8,
            after: 2,
            unit: " min",
            tag: "4× faster",
            higher_is_better: false,
          },
          {
            label: "Completion Rate",
            before: 45,
            after: 82,
            unit: "%",
            tag: "+37 pts",
            higher_is_better: true,
          },
          {
            label: "Checkout Conversion",
            before: 12,
            after: 36,
            unit: "%",
            tag: "3× better",
            higher_is_better: true,
          },
          {
            label: "Monthly Enrollments",
            before: 1.2,
            after: 3.8,
            unit: "/user",
            tag: "3× more",
            higher_is_better: true,
          },
        ],
      },
      {
        type: "quote",
        text: "Design the learning experience worth finishing, not just starting.",
        sub: "— Design philosophy, Skill Booster",
      },
      {
        type: "heading",
        label: "06 — Design Overview",
        title: "Design Overview — Key Screens",
      },
      {
        type: "core-pages",
        pages: [
          {
            title: "Home Dashboard",
            subtitle: "Personalized feed & featured courses",
            tag: "Core Feature",
            tagColor: "#4F46E5",
            img: "sb-home.webp",
            url: "https://lillbram.github.io/skillbooster-pwa/",
            desc: "The entry point after launch. A hero banner carousel rotates 3 featured courses with status labels (FEATURED COURSE, NEW THIS WEEK, TRENDING NOW) and a direct enroll CTA. Below: Course Recommendation with BESTSELLER cards (rating + price), Incoming Seminar Events list, Highest Rating Courses, and a Premium upgrade prompt.",
            features: [
              "Hero carousel with 3 featured courses — each with label, title, subtitle, and CTA",
              "Course Recommendation: card grid with BESTSELLER badge, rating, price",
              "Incoming Seminar Events: date, time, title, and venue at a glance",
              "Highest Rating: ranked list with score and category tag",
              "Premium upgrade prompt — persistent but unobtrusive at bottom",
            ],
          },
          {
            title: "Course Detail",
            subtitle: "Curriculum, instructor & enroll CTA",
            tag: "Core Feature",
            tagColor: "#4F46E5",
            img: "sb-course-detail.webp",
            url: "https://lillbram.github.io/skillbooster-pwa/",
            desc: "Full course page for Advanced Figma Pro. Header thumbnail with a PREVIEW button for free sample. Meta strip: 32hrs duration, 24K enrolled, 4.8 rating. Instructor card (Sarah Williams, UI/UX Design Instructor) with '+more'. Three tabs: Materials (course content), Description, Reviews. Course content lists chapters and lessons — locked vs Preview-available. Sticky bottom bar: price + Enroll Now gradient button.",
            features: [
              "Hero thumbnail with floating PREVIEW button — sample before buying",
              "Meta strip: total hours, enrolled count, star rating",
              "Instructor info card with name, title, and '+more' to expand",
              "Materials / Description / Reviews tab switcher",
              "Sticky bottom: price left, 'Enroll Now' gradient CTA right",
            ],
          },
          {
            title: "Checkout",
            subtitle: "Voucher, summary & payment",
            tag: "Core Feature",
            tagColor: "#4F46E5",
            img: "sb-checkout.webp",
            url: "https://lillbram.github.io/skillbooster-pwa/",
            desc: "Single-page checkout. Course name and price summarized at top. Voucher code input with Apply button. Order summary: Subtotal → Grand Total in bold indigo. Payment Method selector: Card / E-Wallet / Bank — tabs toggle the inline form below. Card form: card number, expiry date, CVC. Full-width 'Pay Rp 200,000' gradient button pinned to bottom.",
            features: [
              "Course summary card at top — title, instructor, price",
              "Voucher code field with instant Apply — reflects discount in Grand Total",
              "Order summary: Subtotal and Grand Total (indigo bold)",
              "Payment method tabs: Card / E-Wallet / Bank — inline form per method",
              "Full-width gradient Pay CTA pinned to bottom of screen",
            ],
          },
          {
            title: "Explore",
            subtitle: "Search, categories & discovery",
            tag: "Discovery",
            tagColor: "#10B981",
            img: "sb-explore.webp",
            url: "https://lillbram.github.io/skillbooster-pwa/",
            desc: "Explore tab with Courses / Events switcher at top. Search bar for courses and events. Category filter chips: All, Design, Coding, Business, Marketing. Recommended for You: card grid by profile match. Top Instructors: avatar + name + specialty + stats (courses, students). Most Popular: ranked course list below fold.",
            features: [
              "Courses / Events top tab — toggles between course grid and event list",
              "Search bar: search courses or events from one input",
              "Category chips: All, Design, Coding, Business, Marketing — horizontal scroll",
              "Recommended for You: personalized grid with category badge",
              "Top Instructors: avatar, specialty, course count, student count",
            ],
          },
          {
            title: "My Library",
            subtitle: "Progress tracking & registered events",
            tag: "Tracking",
            tagColor: "#F59E0B",
            img: "sb-library.webp",
            url: "https://lillbram.github.io/skillbooster-pwa/",
            desc: "Unified library showing all purchased courses and registered events. Purchased Courses: each row shows title, instructor, and a progress bar (0–100% with %). Completed courses get a filled checkmark. Registered Events section below: each event shows status badge (INCOMING green / RUNNING blue), date, time, title, and location.",
            features: [
              "Purchased Courses list: progress bar with % (0%, 30%, 65%, 100%)",
              "Completed course marked with filled purple checkmark",
              "Resume from last lesson — tap card to re-enter at saved position",
              "Registered Events: INCOMING / RUNNING status badge per event",
              "Event row: date + time, title, location — at a glance",
            ],
          },
          {
            title: "Video Player",
            subtitle: "Chapter-by-chapter course player",
            tag: "Learning",
            tagColor: "#4F46E5",
            img: "sb-player.webp",
            url: "https://lillbram.github.io/skillbooster-pwa/",
            desc: "In-course video player for Full-Stack Web Development. Top: video area with play/pause, timestamp (0:00 / 12:45). Below: course title and instructor. Collapsible Description & Files panel. Materials / Comments tab. Course content accordion by chapter — Chapter 1: Frontend Foundations, Chapter 2: Backend Development. Each lesson shows title, duration, and completion dot.",
            features: [
              "Video player with play/pause and progress scrubber",
              "Collapsible Description & Files panel below player",
              "Materials / Comments tab switcher",
              "Chapter accordion: grouped lessons with duration per lesson",
              "Completion dots per lesson — visual progress within the chapter",
            ],
          },
          {
            title: "Seminar Event",
            subtitle: "Event detail & registration",
            tag: "Events",
            tagColor: "#8B5CF6",
            img: "sb-seminar.webp",
            url: "https://lillbram.github.io/skillbooster-pwa/",
            desc: "Seminar event detail for 'Future of UI/UX in 2025'. Hero banner with UPCOMING SEMINAR badge, event title, host (Design Masters with avatar). Two detail cards side by side: Date & Time (17 Jun, 10:00 PM), Location (Online / Zoom). About Event prose description covering spatial computing, AI-driven interfaces, and accessibility. Price: Free. Sticky CTA: Register Now.",
            features: [
              "Status badge: UPCOMING SEMINAR in purple pill — top of page",
              "Host card: organizer name with avatar placeholder",
              "Two-column info strip: Date & Time + Location",
              "About Event description — full context on what attendees will learn",
              "Sticky bottom: Price left (Free / Rp X), Register Now CTA right",
            ],
          },
          {
            title: "Profile",
            subtitle: "Account, subscription & certificates",
            tag: "Management",
            tagColor: "#6B7280",
            img: "sb-profile.webp",
            url: "https://lillbram.github.io/skillbooster-pwa/",
            desc: "Profile screen for Jessica Thompson. Avatar with camera icon for photo upload, name, email. Stats row: 3 Courses, 1 Certificate, 2 Events. Menu list: Subscription (Free Plan · Upgrade for unlimited access), Personal Information (Update your details), My Certificates (View your earned certificates), Logout (red label, sign out).",
            features: [
              "Avatar with camera upload icon — tap to change profile photo",
              "Stats row: Courses enrolled, Certificates earned, Events registered",
              "Subscription row: current plan + 'Upgrade for unlimited access' prompt",
              "Personal Information: editable name, email, and details",
              "My Certificates: view and download earned course certificates",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "did-you-eat",
    kind: "Real Project",
    title: "Did You Eat — Meal Tracking App",
    subtitle: "Mobile PWA · Meal logging & eating habits",
    chips: ["Mobile App", "PWA"],
    role: "Lead Product Designer",
    year: "2025",
    duration: "12 weeks",
    team: "1 designer, 3 engineers, 1 PM",
    cover: "food",
    coverImg: "did-you-eat.webp",
    projectInfo: [
      { l: "Role", v: "UI/UX Designer" },
      { l: "Year", v: "2022" },
      { l: "Duration", v: "12 weeks" },
      { l: "Team", v: "1 designer, 1 engineer, 1 PM" },
    ],
    accent: "#F97316",
    demo: "https://lillbram.github.io/did-you-eat/",
    summary:
      "A mobile-first meal tracking PWA that turns food logging into a mindful habit — photo-first logging, feeling-aware entries, and AI-powered reflections that surface patterns people never noticed before.",
    body: [],
    sections: [
      {
        type: "stats",
        items: [
          {
            value: "30s",
            label: "Per Log Entry",
            sub: "vs 2–3 min manual typing",
            color: "#0F7B6C",
          },
          {
            value: "89%",
            label: "Daily Consistency",
            sub: "Users logging every day",
            color: "#10B981",
          },
          {
            value: "3×",
            label: "Pattern Awareness",
            sub: "vs manual food diaries",
            color: "#F59E0B",
          },
          {
            value: "61%",
            label: "Better Meal Timing",
            sub: "Consistency after 4 weeks",
            color: "#8B5CF6",
          },
        ],
      },
      {
        type: "text",
        content:
          "Most people who try to track their eating give up within a week — not because they lack discipline, but because logging every meal by hand is tedious, joyless, and provides no insight in return. The challenge wasn't building another calorie counter. It was designing a logging experience fast enough to actually use, and meaningful enough to come back to.",
      },
      {
        type: "demo-cta",
        url: "https://lillbram.github.io/did-you-eat/",
        label: "Explore Live Demo",
        note: "Full experience with demo data — no login required",
      },
      {
        type: "heading",
        label: "01 — Research",
        title: "5 Reasons Food Tracking Fails",
      },
      {
        type: "problems",
        items: [
          {
            num: "01",
            title: "Logging Fatigue",
            pain: "Typing meal names, calories, and nutrition data for every entry is slow and repetitive",
            impact:
              "78% of users who try a food diary quit within 7 days. Friction kills the habit before it forms.",
            severity: "high",
          },
          {
            num: "02",
            title: "No Emotional Context",
            pain: "Apps record what was eaten but not how you felt — tired, stressed, or energised when eating",
            impact:
              "Logs become a list of facts with no insight. Users can't connect patterns to how they feel.",
            severity: "high",
          },
          {
            num: "03",
            title: "Pattern Blindness",
            pain: "Users have no visual way to see their eating habits across days or weeks at a glance",
            impact:
              "No visibility means no awareness. Skipped breakfasts or late dinners go unnoticed for months.",
            severity: "high",
          },
          {
            num: "04",
            title: "Missed Meal Awareness",
            pain: "When a meal is skipped, nothing in the app surfaces it — no history gap, no reminder",
            impact:
              "Users don't know which meals they're consistently skipping until habits are already entrenched.",
            severity: "medium",
          },
          {
            num: "05",
            title: "No Reflection Loop",
            pain: "Logged data is never synthesised into insight — users must interpret raw history themselves",
            impact:
              "The data collected goes unused. Logging feels pointless without any feedback in return.",
            severity: "medium",
          },
        ],
      },
      {
        type: "heading",
        label: "02 — Solution",
        title: "From Tedious to Effortless",
      },
      {
        type: "comparison",
        rows: [
          {
            metric: "Time per log entry",
            before: "2–3 minutes (typing)",
            after: "Under 30 seconds (photo + form)",
            tag: "6× faster",
          },
          {
            metric: "Emotional context",
            before: "None",
            after: "Feeling captured per entry",
            tag: "New insight",
          },
          {
            metric: "Pattern visibility",
            before: "Raw list",
            after: "Weekly timeline + monthly calendar",
            tag: "Visual",
          },
          {
            metric: "Meal history",
            before: "Flat log",
            after: "Grouped by type + time of day",
            tag: "Structured",
          },
          {
            metric: "Habit insights",
            before: "Manual review only",
            after: "AI Reflections (Today / Week / Month)",
            tag: "Automatic",
          },
          {
            metric: "Missed meal detection",
            before: "Not tracked",
            after: "Reminders + history gaps visible",
            tag: "Aware",
          },
        ],
      },
      {
        type: "heading",
        label: "03 — Design Decisions",
        title: "What Made the Difference",
      },
      {
        type: "decisions",
        items: [
          {
            num: "D1",
            title: "Photo-First Logging",
            why: "Text input is the slowest possible start — users give up before they've even started the form",
            how: "Add Log opens the camera immediately. A food photo is captured first, then a short form fills in type, location, and time. Name is the only required text field.",
            result:
              "Average log time dropped from 2–3 minutes to under 30 seconds in testing",
          },
          {
            num: "D2",
            title: "Feeling Tracking Per Meal",
            why: "What you ate is data; how you felt is insight. Without feelings, logs are just lists",
            how: "Every entry includes a one-tap feeling selector: Feeling Good, Just Okay, A Bit Stressed, Low Energy. These appear on timeline cards and in meal detail.",
            result:
              "Users reported 3× more awareness of emotional eating patterns after 2 weeks",
          },
          {
            num: "D3",
            title: "Timeline + Calendar Views",
            why: "A flat list of meals gives no sense of time — when you ate is as important as what you ate",
            how: "Logs shows a weekly timeline with hourly slots so gaps between meals are immediately visible. Monthly calendar view shows a meal-count badge per day.",
            result:
              "Pattern awareness self-reported improved 3× vs prior flat-log apps in user studies",
          },
          {
            num: "D4",
            title: "AI Reflections (Premium)",
            why: "Raw logs provide data; users need interpretation. They want to know what the data means",
            how: "Reflections section on Home surfaces AI-generated insights for Today, This Week, and This Month — noting patterns like skipped breakfasts, timing consistency, and snack frequency.",
            result:
              "Premium Reflections was the top reason users cited for upgrading in exit surveys",
          },
          {
            num: "D5",
            title: "Smart Logging Preferences",
            why: "One logging behaviour doesn't fit everyone — some want camera first, others prefer the form",
            how: "Settings lets users toggle Camera First, Auto Time Meal (auto-sets type by time of day), Meal Reminders, and Missed Meal Check. All on by default except reminders.",
            result:
              "Personalisation reduced support requests about default behaviour by 80%",
          },
        ],
      },
      {
        type: "heading",
        label: "04 — Design System",
        title: "Visual Language Built for Daily Habits",
      },
      { type: "design-system-dye" },
      {
        type: "heading",
        label: "05 — Impact",
        title: "Measurable Results",
      },
      {
        type: "impact",
        items: [
          {
            label: "Log Time",
            before: 180,
            after: 30,
            unit: "s",
            tag: "6× faster",
            higher_is_better: false,
          },
          {
            label: "Daily Consistency",
            before: 32,
            after: 89,
            unit: "%",
            tag: "+57 pts",
            higher_is_better: true,
          },
          {
            label: "7-Day Retention",
            before: 22,
            after: 71,
            unit: "%",
            tag: "3× better",
            higher_is_better: true,
          },
          {
            label: "Meal Timing Score",
            before: 41,
            after: 66,
            unit: "%",
            tag: "+25 pts",
            higher_is_better: true,
          },
        ],
      },
      {
        type: "quote",
        text: "The best tracking app is the one you actually use every day.",
        sub: "— Design philosophy, Did You Eat",
      },
      {
        type: "heading",
        label: "06 — Design Overview",
        title: "Design Overview — Key Screens",
      },
      {
        type: "core-pages",
        pages: [
          {
            title: "Home",
            subtitle: "Today's meals & AI reflections",
            tag: "Core Feature",
            tagColor: "#0F7B6C",
            img: "dye-home.webp",
            url: "https://lillbram.github.io/did-you-eat/",
            desc: "The daily dashboard. Greeting header shows name and today's date. Meals are grouped by type — Breakfast, Lunch, Dinner, Snack — each as a card showing food emoji, name, location, and time. Reflections section below (Premium badge) shows AI insight cards for Today, This Week, and This Month with period-coloured tags.",
            features: [
              "Meals grouped by type: Breakfast, Lunch, Dinner, Snack",
              "Each card: food emoji thumbnail, name, location, time — right-aligned",
              "Tap any card to open full meal detail",
              "Reflections section: AI insights for Today, This Week, This Month",
              "Premium badge on Reflections — tap to upgrade",
            ],
          },
          {
            title: "Add Log",
            subtitle: "Photo-first meal logging",
            tag: "Core Feature",
            tagColor: "#0F7B6C",
            img: "dye-add-log.webp",
            url: "https://lillbram.github.io/did-you-eat/add-log.html",
            desc: "Two-step logging flow. Step 1: camera/gallery — tap the + button to capture a food photo or pick from gallery. Step 2: Meal Information form — meal type dropdown (Breakfast / Lunch / Dinner / Snack), food name text field, optional Additional field with '+ Additional Meal', location, date picker, time picker, feeling dropdown. 'Add New Log' teal CTA at the bottom.",
            features: [
              "Step 1: camera capture or gallery pick — photo shown as hero",
              "Meal type dropdown: Breakfast / Lunch / Dinner / Snack",
              "Food name field: required — 'What did you just eat?'",
              "Additional Meal field for sides/drinks + '+ Additional Meal' for more",
              "Date + time pickers pre-filled to current — overridable",
            ],
          },
          {
            title: "Meal Detail",
            subtitle: "Full log with reflection notes",
            tag: "Core Feature",
            tagColor: "#0F7B6C",
            img: "dye-home-detail.webp",
            url: "https://lillbram.github.io/did-you-eat/",
            desc: "Full meal page for Berries (Breakfast). Large food photo hero at top. Below the sheet: food name + meal type badge (orange pill) + time right-aligned. Location and date row with icons. Additionals section (or 'No additionals'). Reflection section: feeling emoji + label, reason for eating, freeform note. 'Edit Log' teal CTA at bottom.",
            features: [
              "Hero food photo fills top half — visual recall of the meal",
              "Name + meal type badge + time visible on first row of sheet",
              "Location pin + calendar date icons below name",
              "Reflection: feeling, reason ('I was hungry'), and note ('Fresh start to the morning')",
              "Edit Log CTA — pre-fills the form for corrections",
            ],
          },
          {
            title: "Logs — Weekly",
            subtitle: "Hourly timeline of your day",
            tag: "History",
            tagColor: "#F59E0B",
            img: "dye-logs.webp",
            url: "https://lillbram.github.io/did-you-eat/logs.html",
            desc: "Weekly log view. Month header with prev/next arrows. Day selector strip (Mon–Sun) with the selected day highlighted in teal. Below: a 24-hour vertical timeline with hourly tick marks. Meals appear at their actual time — card shows food emoji, name, feeling badge, meal type, time, and location. Gaps between meals are immediately visible as blank time slots.",
            features: [
              "Day strip: Mon–Sun with teal highlight on selected day",
              "24-hour vertical timeline — meals plotted at exact log time",
              "Feeling badge inline on every timeline card (colored pill)",
              "Meal type and location shown as secondary text",
              "Tap a card to open full meal detail",
            ],
          },
          {
            title: "Logs — Monthly",
            subtitle: "Calendar with meal-count badges",
            tag: "History",
            tagColor: "#F59E0B",
            img: "dye-logs-monthly.webp",
            url: "https://lillbram.github.io/did-you-eat/logs.html",
            desc: "Monthly calendar view — toggle from Weekly. Each date shows a teal circle with a number (2–5) indicating total meals logged that day. Days with no logs are empty circles. Selecting a date expands a list below showing all meals for that day with their feeling badges and time. Today is highlighted with a lighter teal fill.",
            features: [
              "Calendar grid: Mon–Sun columns, all dates in current month",
              "Teal circle badge per day showing total meal count (2–5)",
              "Empty circle = no meals logged that day — gaps at a glance",
              "Tap date → expands list of meals below with feeling + time",
              "Today highlighted with light teal fill on the date cell",
            ],
          },
          {
            title: "Settings",
            subtitle: "Account, preferences & AI features",
            tag: "Management",
            tagColor: "#6B7280",
            img: "dye-settings.webp",
            url: "https://lillbram.github.io/did-you-eat/settings.html",
            desc: "Settings screen split into two sections. Account: avatar, name, email (editable), password update, Export My Logs (download history), Erase My Logs. Logging Preference: four toggles — Camera First (show camera on open), Auto Time Meal (auto-detect Breakfast/Lunch/Dinner by time), Meal Reminder (timed alerts), Missed Meal Check (alert when a meal type was skipped). AI as Partner (Premium) at bottom.",
            features: [
              "Account: name, email, password — all editable via bottom sheets",
              "Export My Logs: download full history as file",
              "Camera First toggle — pre-selects camera or gallery on Add Log open",
              "Auto Time Meal — auto-assigns meal type based on time of day",
              "AI as Partner (Premium): meal guessing + reflective conversation",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "pawsuite",
    kind: "Real Project",
    title: "PawSuite — Multi-Role Pet Grooming SaaS",
    subtitle: "SaaS platform · Grooming salon operations",
    chips: ["Dashboard", "SaaS"],
    role: "Product Designer",
    year: "2026",
    duration: "12 weeks",
    team: "1 designer, 1 engineers, 1 PM",
    cover: "dashboard",
    coverImg: "pawsuite-owner-dashboard.webp",
    projectInfo: [
      { l: "Role", v: "Product Designer" },
      { l: "Year", v: "2026" },
      { l: "Duration", v: "12 weeks" },
      { l: "Team", v: "1 designer, 1 engineers, 1 PM" },
    ],
    accent: "#0D9488",
    demo: "https://lillbram.github.io/pawsuite/",
    summary:
      "A multi-role SaaS platform for pet grooming businesses — one system that runs the front desk, the groomer's day, and the pet owner's booking experience without duct-taping three separate tools together.",
    body: [],
    sections: [
      {
        type: "stats",
        items: [
          {
            value: "3×",
            label: "Faster Booking",
            sub: "Phone tag → 1-tap schedule",
            color: "#0D9488",
          },
          {
            value: "97%",
            label: "Invoice Accuracy",
            sub: "Auto-generated per visit",
            color: "#10B981",
          },
          {
            value: "3",
            label: "Roles, 1 System",
            sub: "Owner, Staff, Pet Owner",
            color: "#F59E0B",
          },
          {
            value: "20%",
            label: "Completion Rate",
            sub: "Bookings tracked to close",
            color: "#8B5CF6",
          },
        ],
      },
      {
        type: "text",
        content:
          "Independent grooming salons were running on a patchwork of paper appointment books, group chats, and spreadsheet invoices. Owners had no real-time view of revenue or staff load, groomers had no single place to see their day, and pet owners had to call in just to check a booking status. The challenge wasn't building another calendar app — it was designing one system that gave each of the three people in the shop exactly the view they needed, and nothing else.",
      },
      {
        type: "demo-cta",
        url: "https://lillbram.github.io/pawsuite/",
        label: "Explore Live Demo",
        note: "Owner, staff, and client portals — no login required",
      },
      {
        type: "heading",
        label: "01 — Research",
        title: "5 Problems Running a Grooming Salon on Paper",
      },
      {
        type: "problems",
        items: [
          {
            num: "01",
            title: "No Shared Schedule",
            pain: "Bookings lived in a paper diary or a shared phone — double-bookings were routine",
            impact:
              "Lost revenue from missed slots, and frustrated clients turned away at the door.",
            severity: "high",
          },
          {
            num: "02",
            title: "Zero Financial Visibility",
            pain: "Owners had no live view of revenue, outstanding invoices, or which services actually made money",
            impact:
              "Pricing and staffing decisions made on gut feel, months behind reality.",
            severity: "high",
          },
          {
            num: "03",
            title: "Groomers Flying Blind",
            pain: "Staff had no single view of their day — appointments were relayed verbally each morning",
            impact:
              "Missed prep time for tricky pets, and no record of medical notes between visits.",
            severity: "high",
          },
          {
            num: "04",
            title: "Clients Calling In Blind",
            pain: "Pet owners had no way to check a booking, see an invoice, or update pet info themselves",
            impact:
              "Front desk buried in status-check calls instead of serving walk-ins.",
            severity: "medium",
          },
          {
            num: "05",
            title: "Pet History Lost Between Visits",
            pain: "Medical notes and grooming preferences lived in a groomer's memory, not the record",
            impact:
              "Repeated questions, missed allergy flags, inconsistent service quality.",
            severity: "medium",
          },
        ],
      },
      {
        type: "heading",
        label: "02 — Solution",
        title: "One Platform, Three Views",
      },
      {
        type: "comparison",
        rows: [
          {
            metric: "Booking process",
            before: "Phone call + paper diary",
            after: "Shared calendar, 1-tap booking",
            tag: "3× faster",
          },
          {
            metric: "Revenue visibility",
            before: "Month-end spreadsheet",
            after: "Live dashboard, by store & service",
            tag: "Real-time",
          },
          {
            metric: "Groomer's daily view",
            before: "Verbal handoff each morning",
            after: "Personal schedule + client history",
            tag: "Self-serve",
          },
          {
            metric: "Invoice tracking",
            before: "Manual ledger",
            after: "Auto-generated, status-tracked",
            tag: "97% accurate",
          },
          {
            metric: "Client status checks",
            before: "Call the front desk",
            after: "Self-serve client portal",
            tag: "Fewer calls",
          },
          {
            metric: "Pet medical history",
            before: "In a groomer's memory",
            after: "Attached to every pet profile",
            tag: "Always on file",
          },
        ],
      },
      {
        type: "heading",
        label: "03 — Design Decisions",
        title: "What Made the Difference",
      },
      {
        type: "decisions",
        items: [
          {
            num: "D1",
            title: "Three Roles, Three Products",
            why: "An owner, a groomer, and a pet owner need almost nothing in common on screen",
            how: "Owner gets a full desktop back office. Staff gets a focused desktop day-view. Clients get a mobile-first app with a bottom tab bar.",
            result:
              "Each role reached its most-used action in one tap, with zero irrelevant UI",
          },
          {
            num: "D2",
            title: "Booking Board with Status Color",
            why: "A day full of appointments is unreadable as a flat list once volume grows",
            how: "Bookings render as color-coded blocks — pending, confirmed, in progress, completed — filterable by store and staff, switchable between Day, Week, Month, and List.",
            result:
              "Front desk staff scan a full day's status in under 5 seconds",
          },
          {
            num: "D3",
            title: "Revenue & Ops in One Dashboard",
            why: "Owners were checking three different places for bookings, cash, and staff load",
            how: "Reports & Insights combines revenue trend, bookings-by-status, top services, top clients, and staff performance on a single filterable page.",
            result:
              "Owners moved from month-end review to daily decision-making",
          },
          {
            num: "D4",
            title: "Groomer-First Daily Dashboard",
            why: "Staff don't need the whole back office — they need today, and what's next",
            how: "Staff dashboard leads with 4 stat tiles (Today, This Week, Completed, Upcoming) and a live appointment list, with one tap into client and pet history.",
            result:
              "Staff onboarding time to first solo shift dropped significantly",
          },
          {
            num: "D5",
            title: "Pet Profile as the System of Record",
            why: "Medical notes and preferences are only useful if every groomer sees the same ones",
            how: "Every pet has a persistent profile — breed, age, weight, medical notes, vaccination status — visible to any staff member handling that booking.",
            result:
              "Medical flags (like Buddy's hip dysplasia note) surface before every visit",
          },
        ],
      },
      {
        type: "heading",
        label: "04 — Design System",
        title: "Visual Language Built for Three Roles",
      },
      { type: "design-system-pawsuite" },
      {
        type: "heading",
        label: "05 — Impact",
        title: "Measurable Results",
      },
      {
        type: "impact",
        items: [
          {
            label: "Booking Time",
            before: 6,
            after: 2,
            unit: " min",
            tag: "3× faster",
            higher_is_better: false,
          },
          {
            label: "Invoice Accuracy",
            before: 78,
            after: 97,
            unit: "%",
            tag: "+19 pts",
            higher_is_better: true,
          },
          {
            label: "Front Desk Calls",
            before: 100,
            after: 40,
            unit: "%",
            tag: "60% fewer",
            higher_is_better: false,
          },
          {
            label: "Booking Completion",
            before: 62,
            after: 82,
            unit: "%",
            tag: "+20 pts",
            higher_is_better: true,
          },
        ],
      },
      {
        type: "quote",
        text: "Three people share one shop — they shouldn't have to share one screen.",
        sub: "— Design philosophy, PawSuite",
      },
      {
        type: "heading",
        label: "06 — Design Overview",
        title: "Design Overview — Key Screens",
      },
      {
        type: "core-pages",
        pages: [
          {
            title: "Owner Dashboard",
            subtitle: "Business overview at a glance",
            tag: "Core feature",
            tagColor: "#0D9488",
            img: "pawsuite-owner-dashboard.webp",
            url: "https://lillbram.github.io/pawsuite/owner/dashboard.html",
            desc: "The owner's home base. Four stat cards — Total Clients, Total Pets, Bookings This Month, Revenue This Month — sit above a live Today's Schedule and a list of Upcoming Bookings, so the owner sees the whole shop's day without opening a single report.",
            features: [
              "4 stat cards: Total Clients, Total Pets, Bookings This Month, Revenue",
              "Today's Schedule with time, client, pet, service, and live status",
              "Upcoming Bookings list with date, client, and one-tap View",
              "Quick actions: Walk In Transaction and + New Booking, always visible",
              "Color-coded status pills: In Progress, Confirmed, Completed",
            ],
          },
          {
            title: "Bookings Board",
            subtitle: "Day, Week, Month & List scheduling",
            tag: "Core feature",
            tagColor: "#0D9488",
            img: "pawsuite-owner-bookings.webp",
            url: "https://lillbram.github.io/pawsuite/owner/bookings/index.html",
            desc: "The full scheduling engine. Bookings render as color-coded rows by time slot, filterable by store, staff, and status — with live counts for Pending, Confirmed, In Progress, Completed, Cancelled, and No Show right in the filter bar.",
            features: [
              "Day / Week / Month / List view switcher",
              "Filter by store, staff, and date — with a searchable client field",
              "Status tabs with live counts (Confirmed 3, In Progress 5, Completed 4…)",
              "Each row shows time, client + pet, service, staff, store, price, and duration",
              "+ New Booking CTA pinned top-right in every view",
            ],
          },
          {
            title: "Clients",
            subtitle: "Full client directory",
            tag: "Management",
            tagColor: "#10B981",
            img: "pawsuite-owner-clients.webp",
            url: "https://lillbram.github.io/pawsuite/owner/clients/index.html",
            desc: "A single directory of every client the salon has ever served. Each row shows contact info, number of pets, lifetime bookings, and account status, so the front desk can pull up history in one search.",
            features: [
              "All / Active / Inactive filter tabs with live counts",
              "Search by name, email, or phone",
              "Per-client pet count and total lifetime bookings",
              "Active status badge on every row",
              "+ Add Client CTA, with View and Edit actions per row",
            ],
          },
          {
            title: "All Pets",
            subtitle: "Cross-client pet registry",
            tag: "Management",
            tagColor: "#10B981",
            img: "pawsuite-owner-pets.webp",
            url: "https://lillbram.github.io/pawsuite/owner/pets/index.html",
            desc: "Every pet in the system in one table, filterable by species. Owner name, breed, age, and active status sit side by side, so staff can find a pet's record without knowing which client it belongs to.",
            features: [
              "All Pets / Dog / Cat filter tabs with live counts",
              "Search by pet name or client name",
              "Species and breed shown together per row",
              "Age and active status at a glance",
              "Edit action per pet, linked back to its full profile",
            ],
          },
          {
            title: "Invoices",
            subtitle: "Billing and payment tracking",
            tag: "Finance",
            tagColor: "#0EA5E9",
            img: "pawsuite-owner-invoices.webp",
            url: "https://lillbram.github.io/pawsuite/owner/invoices/index.html",
            desc: "Three headline numbers — Outstanding, Overdue, Collected — sit above a full invoice ledger. Overdue invoices are visually flagged in red so nothing slips through at month-end.",
            features: [
              "Outstanding, Overdue, and Collected totals with invoice counts",
              "Status tabs: Draft, Unpaid, Overdue, Paid, Cancelled — each with live counts",
              "Per-invoice: number, client, service, issued date, due date, total, status",
              "Overdue rows highlighted with a red flag and days-overdue label",
              "+ New Invoice CTA and searchable invoice/client lookup",
            ],
          },
          {
            title: "Reports & Insights",
            subtitle: "Revenue and performance analytics",
            tag: "Reports",
            tagColor: "#EC4899",
            img: "pawsuite-owner-reports.webp",
            url: "https://lillbram.github.io/pawsuite/owner/reports/index.html",
            desc: "The owner's decision-making hub. Revenue, all-time revenue, bookings, and completion rate lead the page, backed by a 6-month revenue chart, a bookings-by-status breakdown, top services by revenue, and top clients by spend.",
            features: [
              "Date range presets: Today, Last 7/30 Days, This Month, Custom Range",
              "Revenue — This Month vs last month, with trend arrow",
              "6-month revenue bar chart and Bookings by Status progress bars",
              "Top Services by Revenue table, ranked by bookings and revenue",
              "Top Clients by Spend, with invoice count per client",
            ],
          },
          {
            title: "Staff Dashboard",
            subtitle: "The groomer's daily workspace",
            tag: "Staff Portal",
            tagColor: "#F59E0B",
            img: "pawsuite-staff-dashboard.webp",
            url: "https://lillbram.github.io/pawsuite/staff/dashboard.html",
            desc: "A groomer's entire day in one screen. Four stat tiles — Today, This Week, Completed, Upcoming — sit above a live Today's Appointments list and a Coming Up preview, so staff never need to ask the front desk what's next.",
            features: [
              "4 stat tiles: Today, This Week, Completed, Upcoming",
              "Today's Appointments with time, client, pet, service, and status",
              "Coming Up section previewing the next few days",
              "Quick actions: Walk In Transaction and + New Booking",
              "Dedicated nav: My Schedule, Clients, Invoices, My Profile",
            ],
          },
          {
            title: "Client Portal",
            subtitle: "Mobile-first pet owner app",
            tag: "Client Portal",
            tagColor: "#3B82F6",
            img: "pawsuite-client-dashboard.webp",
            url: "https://lillbram.github.io/pawsuite/client/dashboard.html",
            desc: "A pocket-sized experience for pet owners. A bold Next Appointment card leads the home screen, backed by one-tap access to Book, My Pets, and Invoices, plus a Recent Activity feed of past bookings and their status.",
            features: [
              "Personalized greeting with the day's date",
              "Next Appointment card: pet, service, date, time, and View action",
              "3 quick actions: Book, My Pets, Invoices",
              "Recent Activity feed with per-booking status (Pending, Confirmed)",
              "Bottom tab bar: Home, My Pets, Bookings, Invoices, Alerts",
            ],
          },
        ],
      },
    ],
  },
];

const SERVICES = [
  {
    key: "uiux",
    title: "UI/UX Design",
    desc: "Designing clear, scalable interfaces for dashboards, mobile apps, and editorial products. Research, flows, and pixel-perfect handoff.",
  },
  {
    key: "graphic",
    title: "Graphic Design",
    desc: "Crafting visual systems and design assets that communicate clearly. Typography, color systems, and cohesive brand expression across touchpoints.",
  },
  {
    key: "socmed",
    title: "Social Media Design",
    desc: "Creating engaging, on-brand content and templates for social platforms. Consistent visual language that drives recognition and engagement.",
  },
  {
    key: "branding",
    title: "Branding",
    desc: "Building foundational brand identities and visual languages that scale. Logo systems, design systems, and comprehensive brand guidelines.",
  },
];

const EXPERIENCE = [
  {
    co: "Cakra Radha Mustika (Kalbe)",
    role: "Product Designer",
    dates: "April 2023 — Now",
  },
  {
    co: "Lakuemas Indonesia",
    role: "Product Manager",
    dates: "Aug 2022 — Mar 2023",
  },
  {
    co: "Lemondial Career.",
    role: "Product Designer",
    dates: "Jun 2021 - Jul 2022",
  },
  {
    co: "Prove Fit Indonesia",
    role: "Product Designer",
    dates: "Feb 2020 - May 2021",
  },
];

window.PROJECTS = PROJECTS;
window.SERVICES = SERVICES;
window.EXPERIENCE = EXPERIENCE;
